// <auto-generated />
using System;
using EindCaseBelastingDienst.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EindCaseBelastingDienst.Migrations
{
    [DbContext(typeof(CursusContext))]
    [Migration("20210323083736_ForeignKeyMigration")]
    partial class ForeignKeyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EindCaseBelastingDienst.Models.Cursus", b =>
                {
                    b.Property<int>("CursusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CursusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duur")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursusId");

                    b.ToTable("Cursussen");
                });

            modelBuilder.Entity("EindCaseBelastingDienst.Models.CursusInstantie", b =>
                {
                    b.Property<int>("CursusInstantieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CursusTijd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CursussenCursusId")
                        .HasColumnType("int");

                    b.HasKey("CursusInstantieId");

                    b.HasIndex("CursussenCursusId");

                    b.ToTable("CursusInstanties");
                });

            modelBuilder.Entity("EindCaseBelastingDienst.Models.CursusInstantie", b =>
                {
                    b.HasOne("EindCaseBelastingDienst.Models.Cursus", "Cursussen")
                        .WithMany()
                        .HasForeignKey("CursussenCursusId");

                    b.Navigation("Cursussen");
                });
#pragma warning restore 612, 618
        }
    }
}
