// <auto-generated />
using EindCaseBelastingDienst.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EindCaseBelastingDienst.Migrations
{
    [DbContext(typeof(CursusContext))]
    [Migration("20210322114822_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EindCaseBelastingDienst.Models.Cursussen", b =>
                {
                    b.Property<string>("CursusCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Duur")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursusCode");

                    b.ToTable("Cursussen");
                });
#pragma warning restore 612, 618
        }
    }
}
