// <auto-generated />
using EindCaseBelastingDienst.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EindCaseBelastingDienst.Migrations
{
    [DbContext(typeof(CursusContext))]
    partial class CursusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EindCaseBelastingDienst.Models.Cursus", b =>
                {
                    b.Property<int>("CursusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CursusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CursusInstantieId")
                        .HasColumnType("int");

                    b.Property<int>("Duur")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursusId");

                    b.HasIndex("CursusInstantieId");

                    b.ToTable("Cursussen");
                });

            modelBuilder.Entity("EindCaseBelastingDienst.Models.CursusInstantie", b =>
                {
                    b.Property<int>("CursusInstantieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CursusTijd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursusInstantieId");

                    b.ToTable("CursusInstanties");
                });

            modelBuilder.Entity("EindCaseBelastingDienst.Models.Cursus", b =>
                {
                    b.HasOne("EindCaseBelastingDienst.Models.CursusInstantie", "CursusInstantie")
                        .WithMany("Cursussen")
                        .HasForeignKey("CursusInstantieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CursusInstantie");
                });

            modelBuilder.Entity("EindCaseBelastingDienst.Models.CursusInstantie", b =>
                {
                    b.Navigation("Cursussen");
                });
#pragma warning restore 612, 618
        }
    }
}
